In [3]:
import pandas as pd
nlst = pd.read_csv("/data/vedant/MIND/benchmarks/nlst/greedy_registration_mind_masked/keypoint_distances.csv")
nlst.describe()

       dist_initial_physical  dist_final_physical
count             210.000000           210.000000
mean                9.079160             1.090886
std                 3.217559             0.727018
min                 3.416131             0.636243
25%                 6.901791             0.822876
50%                 8.569040             0.925582
75%                10.597270             1.144868
max                21.484379             7.655885

In [5]:
nlst["percentage improvement"] = (nlst["dist_initial_physical"] - nlst["dist_final_physical"])/nlst["dist_initial_physical"]

In [15]:
# sort nlst by percentage improvement and take top 50 pairs
nlst_sorted = nlst.sort_values(by="percentage improvement", ascending=True)
top_50 = nlst_sorted.head(50)
top_50_csv = top_50[["case", "fixed_image", "moving_image"]]
top_50_csv.to_csv("/data/vedant/MIND/notebooks/nlst_choosen_pairs/worst_50.csv", index=False)

In [16]:
top_50

,case,fixed_image,moving_image,dist_initial_physical,dist_final_physical,percentage improvement
64,NLST_0065,NLST_0065_0000.nii.gz,NLST_0065_0001.nii.gz,3.416131,3.606490,-0.055724
32,NLST_0033,NLST_0033_0000.nii.gz,NLST_0033_0001.nii.gz,11.798880,7.394094,0.373322
116,NLST_0206,NLST_0206_0000.nii.gz,NLST_0206_0001.nii.gz,16.399956,7.655885,0.533176
82,NLST_0083,NLST_0083_0000.nii.gz,NLST_0083_0001.nii.gz,4.902272,1.424821,0.709355
6,NLST_0007,NLST_0007_0000.nii.gz,NLST_0007_0001.nii.gz,8.406698,2.249646,0.732398
123,NLST_0213,NLST_0213_0000.nii.gz,NLST_0213_0001.nii.gz,8.148745,1.823613,0.776209
91,NLST_0092,NLST_0092_0000.nii.gz,NLST_0092_0001.nii.gz,5.558337,1.226857,0.779276
177,NLST_0267,NLST_0267_0000.nii.gz,NLST_0267_0001.nii.gz,10.834610,2.303122,0.787429
96,NLST_0097,NLST_0097_0000.nii.gz,NLST_0097_0001.nii.gz,5.888572,1.243448,0.788837
169,NLST_0259,NLST_0259_0000.nii.gz,NLST_0259_0001.nii.gz,7.769389,1.602938,0.793686
134,NLST_0224,NLST_0224_0000.nii.gz,NLST_0224_0001.nii.gz,13.135809,2.599183,0.802130
77,NLST_0078,NLST_0078_0000.nii.gz,NLST_0078_0001.nii.gz,4.469747,0.842848,0.811433
9,NLST_0010,NLST_0010_0000.nii.gz,NLST_0010_0001.nii.gz,4.010015,0.754930,0.811739
168,NLST_0258,NLST_0258_0000.nii.gz,NLST_0258_0001.nii.gz,7.990438,1.443867,0.819301
0,NLST_0001,NLST_0001_0000.nii.gz,NLST_0001_0001.nii.gz,5.505039,0.974315,0.823014
163,NLST_0253,NLST_0253_0000.nii.gz,NLST_0253_0001.nii.gz,8.705367,1.465537,0.831651
35,NLST_0036,NLST_0036_0000.nii.gz,NLST_0036_0001.nii.gz,4.385346,0.727379,0.834134
62,NLST_0063,NLST_0063_0000.nii.gz,NLST_0063_0001.nii.gz,4.320176,0.714810,0.834542
43,NLST_0044,NLST_0044_0000.nii.gz,NLST_0044_0001.nii.gz,4.564023,0.754812,0.834617
60,NLST_0061,NLST_0061_0000.nii.gz,NLST_0061_0001.nii.gz,5.493354,0.904585,0.835331
117,NLST_0207,NLST_0207_0000.nii.gz,NLST_0207_0001.nii.gz,10.790130,1.771808,0.835794
40,NLST_0041,NLST_0041_0000.nii.gz,NLST_0041_0001.nii.gz,5.390788,0.880441,0.836677
54,NLST_0055,NLST_0055_0000.nii.gz,NLST_0055_0001.nii.gz,5.443806,0.885045,0.837422
55,NLST_0056,NLST_0056_0000.nii.gz,NLST_0056_0001.nii.gz,5.089289,0.794137,0.843959
14,NLST_0015,NLST_0015_0000.nii.gz,NLST_0015_0001.nii.gz,4.690273,0.725328,0.845355
73,NLST_0074,NLST_0074_0000.nii.gz,NLST_0074_0001.nii.gz,4.880808,0.739055,0.848579
41,NLST_0042,NLST_0042_0000.nii.gz,NLST_0042_0001.nii.gz,5.438145,0.823188,0.848627
47,NLST_0048,NLST_0048_0000.nii.gz,NLST_0048_0001.nii.gz,5.453215,0.822771,0.849122
92,NLST_0093,NLST_0093_0000.nii.gz,NLST_0093_0001.nii.gz,5.621613,0.845998,0.849510
181,NLST_0271,NLST_0271_0000.nii.gz,NLST_0271_0001.nii.gz,7.889727,1.185057,0.849797
25,NLST_0026,NLST_0026_0000.nii.gz,NLST_0026_0001.nii.gz,5.292944,0.783486,0.851975
38,NLST_0039,NLST_0039_0000.nii.gz,NLST_0039_0001.nii.gz,5.594433,0.823411,0.852816
51,NLST_0052,NLST_0052_0000.nii.gz,NLST_0052_0001.nii.gz,5.228823,0.769318,0.852870
160,NLST_0250,NLST_0250_0000.nii.gz,NLST_0250_0001.nii.gz,7.958735,1.164407,0.853694
89,NLST_0090,NLST_0090_0000.nii.gz,NLST_0090_0001.nii.gz,6.861473,1.002277,0.853927
65,NLST_0066,NLST_0066_0000.nii.gz,NLST_0066_0001.nii.gz,9.877977,1.439951,0.854226
99,NLST_0100,NLST_0100_0000.nii.gz,NLST_0100_0001.nii.gz,5.923855,0.857779,0.855199
17,NLST_0018,NLST_0018_0000.nii.gz,NLST_0018_0001.nii.gz,5.355341,0.774316,0.855412
103,NLST_0104,NLST_0104_0000.nii.gz,NLST_0104_0001.nii.gz,7.512770,1.082888,0.855860
19,NLST_0020,NLST_0020_0000.nii.gz,NLST_0020_0001.nii.gz,5.450448,0.783711,0.856212
30,NLST_0031,NLST_0031_0000.nii.gz,NLST_0031_0001.nii.gz,5.838575,0.834344,0.857098
79,NLST_0080,NLST_0080_0000.nii.gz,NLST_0080_0001.nii.gz,5.364316,0.762297,0.857895
182,NLST_0272,NLST_0272_0000.nii.gz,NLST_0272_0001.nii.gz,8.754881,1.242756,0.858050
53,NLST_0054,NLST_0054_0000.nii.gz,NLST_0054_0001.nii.gz,5.192835,0.736539,0.858162
57,NLST_0058,NLST_0058_0000.nii.gz,NLST_0058_0001.nii.gz,4.976238,0.698477,0.859637
140,NLST_0230,NLST_0230_0000.nii.gz,NLST_0230_0001.nii.gz,10.213978,1.425210,0.860465
39,NLST_0040,NLST_0040_0000.nii.gz,NLST_0040_0001.nii.gz,5.593849,0.779332,0.860681
22,NLST_0023,NLST_0023_0000.nii.gz,NLST_0023_0001.nii.gz,5.580326,0.765292,0.862859
85,NLST_0086,NLST_0086_0000.nii.gz,NLST_0086_0001.nii.gz,5.633422,0.766581,0.863923
18,NLST_0019,NLST_0019_0000.nii.gz,NLST_0019_0001.nii.gz,5.239229,0.710058,0.864473